In [9]:
import pandas as pd
import matplotlib.pyplot as plt
import math
import numpy as np
import seaborn as sns
from collections import Counter
from pyinform import transfer_entropy
from pyinform import mutual_info
colors_to_numbers = {'gru': 0, 'pty': 1, 'jfk': 2, 'lax': 3, 'las': 4, 'lis': 5, 'bru': 6, 'hkg': 7, 'icn': 8, 'mex': 9}

In [36]:
#get the transition state for a particular cell 
#instead of getting the entire dataframe, lets only look at the neighbors 
#lets grab them and see if we can find any similarities in them 

num_df = 199
moore_neighborhood_states = [0]

for baseline_cell in range(150,151): #cells in range 1 --> 401
    mutual_info_state_transitions_same_timestep = [0] * 400
    print('BaseLine Cell: ',baseline_cell)
    initialization_flag = 1
    for df_counter in range(0, num_df):
        # if df_counter % 20 == 0:
        #     print(df_counter)
        df = pd.read_csv(r'C:\Users\matth\PhD\Fall 2024\SSIE 501-SSE 440\Programming\ScrapingOutput\DataCollector4\blackbox_'+str(df_counter)+'.csv').replace(colors_to_numbers)
        baseline_cell_colors = []
        baseline_cell_transition_index =[]
        X = list(df.iloc[:,baseline_cell])
        baseline_cell_colors.append(X[0])
        baseline_cell_transition_index.append(0)
        for j in range(1,len(X)):
            if X[j] != X[j-1]:
                baseline_cell_colors.append(X[j]) #appends the color to the list at the time of the change 
                baseline_cell_transition_index.append(j) #j is where it changes we are most likely going to want the step right BEFORE it changes 
        for i in range(0,len(baseline_cell_colors)-1):
            if baseline_cell_colors[i] == 1  and baseline_cell_colors[i+1] == 4:
                print(baseline_cell_transition_index[i+1])
                if initialization_flag ==1:
                    moore_neighborhood_states[0] = list(df.iloc[baseline_cell_transition_index[i+1]-1,[baseline_cell-11,baseline_cell-10,baseline_cell-9,baseline_cell-1,baseline_cell,baseline_cell+1,baseline_cell+9,baseline_cell+10,baseline_cell+11]])
                    print(moore_neighborhood_states)
                    initialization_flag = 0
                else:
                    moore_neighborhood_states.append(list(df.iloc[baseline_cell_transition_index[i+1]-1,[baseline_cell-11,baseline_cell-10,baseline_cell-9,baseline_cell-1,baseline_cell,baseline_cell+1,baseline_cell+9,baseline_cell+10,baseline_cell+11]]))
        
    for neighborhood in moore_neighborhood_states:
        neighborhood = np.reshape(neighborhood, (3,3))
        print(neighborhood)
        print('-----------------')
        # for index,c in enumerate(baseline_cell_colors):
        #     #print(baseline_cell_transition_index[index],c,format(c,'04b'))
        #     print('{:1} {:5} {}'.format(c,format(c,'04b'),baseline_cell_transition_index[index],))
        # print('---------------------')
    # print(comparator_state)

BaseLine Cell:  150
1070
[[0, 0, 0, 0, 1, 7, 0, 1, 3]]
1223
669
142
152
867
84
363
365
315
1709
202
280
1002
236
361
1260
1
124
878
1318
1368
228
201
278
827
683
1017
1545
77
348
205
1312
636
856
1522
531
1403
1188
1338
230
1369
1324
1195
1350
10
1147
[[0 0 0]
 [0 1 7]
 [0 1 3]]
-----------------
[[1 0 0]
 [3 1 0]
 [3 4 0]]
-----------------
[[1 3 2]
 [6 1 0]
 [6 3 8]]
-----------------
[[1 8 0]
 [2 1 2]
 [1 0 3]]
-----------------
[[1 0 1]
 [1 1 1]
 [1 1 1]]
-----------------
[[1 8 0]
 [1 1 1]
 [2 9 0]]
-----------------
[[3 0 4]
 [4 1 2]
 [2 0 5]]
-----------------
[[1 1 7]
 [9 1 6]
 [1 1 0]]
-----------------
[[0 2 2]
 [1 1 6]
 [1 1 0]]
-----------------
[[5 0 2]
 [6 1 1]
 [2 0 4]]
-----------------
[[0 1 3]
 [0 1 3]
 [3 0 2]]
-----------------
[[1 0 0]
 [6 1 9]
 [4 6 5]]
-----------------
[[7 0 1]
 [0 1 0]
 [2 0 5]]
-----------------
[[0 0 0]
 [0 1 0]
 [0 4 4]]
-----------------
[[1 1 2]
 [2 1 3]
 [8 2 1]]
-----------------
[[0 1 5]
 [3 1 3]
 [1 5 1]]
-----------------
[[0 7 4]
 [4

In [40]:
#get all the transistions of a particular cell from state a to b 
#get the dataframe state at the moment before the state changes <-- this is the base 
#see the next time the same transition happens
#get the dataframe jsut before it happens, again
#mark all the cells that have the same value when this happened 
#repeat until either no cells are the same or some dcells are the same 

num_df = 199
comparator_state = [0]*400
comparator_state2 = 0
comparator_state3 = 0 
for baseline_cell in range(346,347): #cells in range 1 --> 401
    mutual_info_state_transitions_same_timestep = [0] * 400
    print('BaseLine Cell: ',baseline_cell)
    initialization_flag = 1
    secondary_flag = 1
    for df_counter in range(0, num_df):
        # if df_counter % 20 == 0:
        #     print(df_counter)
        df = pd.read_csv(r'C:\Users\matth\PhD\Fall 2024\SSIE 501-SSE 440\Programming\ScrapingOutput\DataCollector4\blackbox_'+str(df_counter)+'.csv').replace(colors_to_numbers)
        baseline_cell_colors = []
        baseline_cell_transition_index =[]
        X = list(df.iloc[:,baseline_cell])
        baseline_cell_colors.append(X[0])
        baseline_cell_transition_index.append(0)
        for j in range(1,len(X)):
            if X[j] != X[j-1]:
                baseline_cell_colors.append(X[j]) #appends the color to the list at the time of the change 
                baseline_cell_transition_index.append(j) #j is where it changes we are most likely going to want the step right BEFORE it changes 
        for i in range(0,len(baseline_cell_colors)-1):
            if baseline_cell_colors[i] == 2  and baseline_cell_colors[i+1] == 1:
                print(baseline_cell_transition_index[i+1])
                if initialization_flag == 1:
                    comparator_state = list(df.iloc[baseline_cell_transition_index[i+1]-1,1:])
                    initialization_flag = 0
                elif secondary_flag == 1 :
                    comparator_state2 = list(df.iloc[baseline_cell_transition_index[i+1]-1,1:])
                    secondary_flag = 0 
                else:
                    list_c=[[a, b] for a, b in zip(comparator_state, comparator_state2)]
                    comparator_state3 = list(df.iloc[baseline_cell_transition_index[i+1]-1,1:])
                    #$comparator_state = [val1 if val1 == val2 else 11 for val1, val2 in zip(comparator_state, comparator_state3)]
                    for index,elem in enumerate(list_c):
                        if comparator_state3[index] == list_c[index][0] or comparator_state3[index] == list_c[index][1]:
                            continue
                        else:
                            list_c[index] = [11,11]
        for index,c in enumerate(baseline_cell_colors):
            #print(baseline_cell_transition_index[index],c,format(c,'04b'))
            print('{:1} {:5} {}'.format(c,format(c,'04b'),baseline_cell_transition_index[index],))
        print('---------------------')
    print(comparator_state)


BaseLine Cell:  346
9 1001  0
---------------------
0 0000  0
1 0001  171
2 0010  331
3 0011  334
4 0100  417
5 0101  418
6 0110  462
7 0111  483
8 1000  640
9 1001  1417
---------------------
8 1000  0
9 1001  55
---------------------
4 0100  0
1 0001  194
2 0010  397
3 0011  413
4 0100  498
5 0101  635
6 0110  662
7 0111  828
8 1000  946
9 1001  986
---------------------
5 0101  0
6 0110  96
7 0111  118
8 1000  201
9 1001  221
---------------------
8 1000  0
9 1001  53
---------------------
8 1000  0
9 1001  114
---------------------
2 0010  0
3 0011  44
4 0100  313
5 0101  404
6 0110  498
7 0111  539
8 1000  633
9 1001  728
---------------------
4 0100  0
5 0101  147
6 0110  173
7 0111  198
8 1000  199
9 1001  291
---------------------
3 0011  0
4 0100  256
5 0101  307
6 0110  333
7 0111  339
8 1000  371
9 1001  442
---------------------
4 0100  0
5 0101  47
6 0110  57
7 0111  104
8 1000  122
9 1001  426
---------------------
9 1001  0
---------------------
7 0111  0
8 1000  12
9 10

In [39]:
a = [1,2,3,4,4]
for index,elem in enumerate(a):
    print(elem)

1
2
3
4
4
